=== kylesm/JWhirli/src/main/resources/strategies.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
	targetNamespace="http://www.botcave.com" 
	elementFormDefault="qualified">
<xs:element name="strategies">
<xs:complexType>
<xs:sequence>
<xs:element name="strategy" minOccurs="1">
	<xs:complexType>
		<xs:attribute name="name" type="xs:string" use="required" />
		<xs:all>
			<xs:element name="a" type="xs:decimal" />
			<xs:element name="b" type="xs:decimal" />
			<xs:element name="c" type="xs:decimal" />
			<xs:element name="d" type="xs:decimal" />
			<xs:element name="velmax">
				<xs:simpleType>
					<xs:restriction base="xs:decimal">
						<xs:minInclusive value="" />
						<xs:maxInclusive value="" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="old_coeff" type="xs:decimal">
				<xs:simpleType>
					<xs:restriction base="xs:decimal">
						<xs:minInclusive value="" />
						<xs:maxInclusive value="" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="dist_coeff" type="xs:decimal">
				<xs:simpleType>
					<xs:restriction base="xs:decimal">
						<xs:minInclusive value="" />
						<xs:maxInclusive value="" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>

			<xs:element name="vdistmax" type="xs:decimal">
				<xs:simpleType>
					<xs:restriction base="xs:decimal">
						<xs:minInclusive value="" />
						<xs:maxInclusive value="" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="color_rgb" value="xs:string">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:pattern value="[0-9]{6}" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="rand_deflection" value="xs:integer">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="0" />
						<xs:maxInclusive value="360" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="rand_moves" value="xs:integer">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="1" />
						<xs:maxInclusive value="1000" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="num_strat_whirlis" value="xs:integer">
				<xs:simpleType>
					<xs:restriction base="xs:integer">
						<xs:minInclusive value="0" />
						<xs:maxInclusive value="1000" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:all>
	</xs:complexType>
</xs:element>
</xs:sequence>
</xs:complexType>
</xs:element>
</xs:schema>

=== kylesm/JWhirli/src/main/resources/strategies.xml
<?xml version="1.0"?>
<strategies 
	xmlns="http://www.botcave.com" 
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.botcave.com strategies.xsd">
	<strategy name="strategy1">
		<a>2.0</a>
		<b>1.0</b>
		<c>3.0</c>
		<d>1.0</d>
		<velmax>1.0</velmax>
		<old_coeff>0.8</old_coeff>
		<dist_coeff>0.2</dist_coeff>
		<vdistmax>20.0</vdistmax>
		<color_rgb>123233</color_rgb>
		<rand_deflection>30</rand_deflection>
		<rand_moves>120</rand_moves>
		<num_strat_whirlis>5</num_strat_whirlis>
	</strategy>
	<strategy name="strategy2">
		<a>2.0</a>
		<b>4.0</b>
		<c>2.5</c>
		<d>4.0</d>
		<velmax>2.0</velmax>
		<old_coeff>0.8</old_coeff>
		<dist_coeff>0.2</dist_coeff>
		<vdistmax>20.0</vdistmax>
		<color_rgb>163833</color_rgb>
		<rand_deflection>180</rand_deflection>
		<rand_moves>45</rand_moves>
		<num_strat_whirlis>5</num_strat_whirlis>
	</strategy>
	<strategy name="strategy3">
		<a>2.0</a>
		<b>16.0</b>
		<c>2.37</c>
		<d>16.0</d>
		<velmax>1.0</velmax>
		<old_coeff>0.8</old_coeff>
		<dist_coeff>0.2</dist_coeff>
		<vdistmax>20.0</vdistmax>
		<color_rgb>320000</color_rgb>
		<rand_deflection>180</rand_deflection>
		<rand_moves>45</rand_moves>
		<num_strat_whirlis>5</num_strat_whirlis>
	</strategy>
</strategies>
